### DISCUSSION TITLE
How to use --exclude-if-present .exclude_from_backup

### DISCUSSION THREAD

**Discussion by jontyms** [cupcakearmy/autorestic#100] [Q&A] [answered]
--exclude-if-present .exclude_from_backup

**Comment by jontyms** [comment, marked as answer]
```
locations:
  home:
    from: /home/
    to:
    - remote
    options:
      backup:
        exclude-if-present: .exclude_from_backup
```
