### DISCUSSION TITLE
Exclude dirs

### DISCUSSION THREAD

**Discussion by 12nick12** [cupcakearmy/autorestic#102] [Q&A] [answered]
This is the command I currently use
/opt/Restic-backup/bin/restic --exclude={/dev,/media,/mnt,/proc,/run,/sys,/tmp,/var/tmp,/var/lib/mysql,/swap*} backup

From https://github.com/cupcakearmy/autorestic/discussions/100

Would I just add the following? 
 options:
      backup:
        exclude: {/dev,/media,/mnt,/proc,/run,/sys,/tmp,/var/tmp,/var/lib/mysql,/swap*}

**Comment by cupcakearmy** [comment, marked as answer]
Sry for the late answer. That syntax is usually bash/zsh/fish syntax, which I think is not uspported by restic. You can pass them as array.

```yaml
options:
  backup:
    exclude:
      - /dev
      - /media
      - ...
```
