### DISCUSSION TITLE
Global Before Hooks

### DISCUSSION THREAD

**Discussion by jshank** [cupcakearmy/autorestic#143] [Q&A]
I'd like to execute a few hooks commands before any backup runs. I've configured the following but the `before` commands aren't run. The idea is to wake my desktop computer (running restserver) as a local backup target right before starting backups. 

```yaml
global:
  hooks:
    before:
    - etherwake -b aa:bb:cc:11:22:33
    - sleep 5
 ```
