### DISCUSSION TITLE
Backup gets stuck

### DISCUSSION THREAD

**Discussion by KaiDevrim** [cupcakearmy/autorestic#153] [Q&A]
Hello, so I am running autorestic for the first time on a backup server vm and this is my config
```yml
backends:
  kaidrive:
    type: rclone
    path: kaidrive:restic/
    key: {REDACTED}
locations:
  home:
    from:
    - /mnt/backups/dump
    - /mnt/backups/ct
    - /mnt/backups/vm
    to:
    - kaidrive
version: 2
```

it gets stuck like this:

```
kai@pbs ~> autorestic backup -avvv
Using config:    /home/kai/.autorestic.yml
Using lock:      /home/kai/.autorestic.lock.yml


    Backing up location "home"

Backend: kaidrive
> Executing: /usr/local/bin/restic backup --tag ar:location:home /mnt/backups/dump /mnt/backups/ct /mnt/backups/vm
```
