### DISCUSSION TITLE
Error: nothing selected, aborting

### DISCUSSION THREAD

**Discussion by sebdanielsson** [cupcakearmy/autorestic#183] [Q&A] [answered]
I can't figure out why autorestic won't run...

Here's my .autorestic.yml

``` yaml
version: 2
locations:
  docker:
    from:
      - /compose
      - /var/lib/docker/volumes
    to:
      - bb
backends:
  bb:
    type: b2
    path: restic-linode1:backup/docker
```

Here's the command output.
``` sh
❯ autorestic check
Using config: 	 /root/.config/autorestic/.autorestic.yml
Using env:	 /root/.config/autorestic/.autorestic.env
Using lock:	 /root/.config/autorestic/.autorestic.lock.yml
Initializing backend "bb"...
Everything is fine.
```

``` sh
❯ autorestic backup -v
Using config paths: . /root /root/.config/autorestic
Using config: 	 /root/.config/autorestic/.autorestic.yml
Using env:	 /root/.config/autorestic/.autorestic.env
Using lock:	 /root/.config/autorestic/.autorestic.lock.yml
Error: nothing selected, aborting
```
