### DISCUSSION TITLE
Allow backends to fail/be skipped

### DISCUSSION THREAD

**Discussion by varac** [cupcakearmy/autorestic#185] [Ideas]
I'd like to always backup to my remote location, and when I'm at home I'd also like to backup a my local NAS.
It would be great if Autorestic could be configured for this in a way that it doesn't fail if the second location is not available.
Maybe a backend config like this could do it:

```
backends:
  remote:
    type: sftp 
    path: ...
  local: 
    type: sftp
    path: ...
    only_if:
      cmd: check_local_avail.sh
      allow_fail: true
```
      
When the script `check_local_avail.sh` fails, and `only_if.allow_fail` is set to `true` autorestic should (silently) succeed.
What do you think ?
