### DISCUSSION TITLE
Need some help with hooks not triggering healthchecks

### DISCUSSION THREAD

**Discussion by ovizii** [cupcakearmy/autorestic#212] [General]
I used the example from here: https://autorestic.vercel.app/examples#use-hooks-to-integrate-with-healthchecks and this is how autorestic is triggered via crontab:

`*/5 * * * * autorestic -c /root/autorestic/.autorestic.yml --ci cron >/dev/null 2>&1`

here is my .autorestic.yml with redacted sensitive information:

```
extras:                                                                                                                                                                                                                                                                                                              
  healthchecks: &healthchecks                                                                                                                                                                                                                                                                                        
    hooks:                                                                                                                                                                                                                                                                                                           
      before:                                                                                                                                                                                                                                                                                                        
        - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Starting backup for location: ${AUTORESTIC_LOCATION}" https://healthchecks.my.domain/ping/123-123-123-123-123/start'                                                                                                  
      failure:                                                                                                                                                                                                                                                                                                       
        - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Backup failed for location: ${AUTORESTIC_LOCATION}" https://healthchecks.my.domain/ping/123-123-123-123-123/fail'                                                                                                     
      success:                                                                                                                                                                                                                                                                                                       
        - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Backup successful for location: ${AUTORESTIC_LOCATION}" https://healthchecks.my.domain/ping/123-123-123-123-123'                                                                                                      
global:                                                                                                                                                                                                                                                                                                              
  forget:                                                                                                                                                                                                                                                                                                            
#    keep-last: 4 # always keep at least X snapshots                                                                                                                                                                                                                                                                 
    keep-hourly: 4 # keep X last hourly snapshots                                                                                                                                                                                                                                                                    
    keep-daily: 7 # keep X last daily snapshots                                                                                                                                                                                                                                                                      
    keep-weekly: 4 # keep X last weekly snapshots                                                                                                                                                                                                                                                                    
    keep-monthly: 12 # keep X last monthly snapshots                                                                                                                                                                                                                                                                 
    keep-yearly: 7 # keep X last yearly snapshots                                                                                                                                                                                                                                                                    
#    keep-within: '1w' # keep snapshots from the last X weeks                                                                                                                                                                                                                                                        
backends:                                                                                                                                                                                                                                                                                                            
  s3-ict:                                                                                                                                                                                                                                                                                                            
    type: s3                                                                                                                                                                                                                                                                                                         
    path: http://my.minio.tld/documents-backup                                                                                                                                                                                                                                                                
    key: supersecretkey                                                                                                                                                                                                                       
    env:                                                                                                                                                                                                                                                                                                             
      aws_access_key_id: supersecretid                                                                                                                                                                                                                                                                                         
      aws_secret_access_key: supersecretaccesskey                                                                                                                                                                                                                                                        
    rest:                                                                                                                                                                                                                                                                                                            
      user: ""                                                                                                                                                                                                                                                                                                       
      password: ""                                                                                                                                                                                                                                                                                                   
    options: {}                                                                                                                                                                                                                                                                                                      
locations:                                                                                                                                                                                                                                                                                                           
  documents:                                                                                                                                                                                                                                                                                                         
    <<: *healthchecks                                                                                                                                                                                                                                                                                                
    from:                                                                                                                                                                                                                                                                                                            
      - /sixer/Documents                                                                                                                                                                                                                                                                                             
    to:                                                                                                                                                                                                                                                                                                              
      - s3-ict                                                                                                                                                                                                                                                                                                       
    forget: prune # Or only "yes" if you don't want to prune                                                                                                                                                                                                                                                         
    hooks:                                                                                                                                                                                                                                                                                                           
      dir: ""                                                                                                                                                                                                                                                                                                        
      before: []                                                                                                                                                                                                                                                                                                     
      after: []                                                                                                                                                                                                                                                                                                      
      success: []                                                                                                                                                                                                                                                                                                    
      failure: []                                                                                                                                                                                                                                                                                                    
    cron: '0 * * * *' #every full hour                                                                                                                                                                                                                                                                               
    options: {}                                                                                                                                                                                                                                                                                                      
version: 2 
```

And just in case you are wondering who butchered this yml file, it wasn't me, that was autorestic's doing when it generated the keys.
