### DISCUSSION TITLE
Docker volumes with REST backend

### DISCUSSION THREAD

**Discussion by bdelcamp** [cupcakearmy/autorestic#278] [Q&A]
I'm trying to backup my docker volumes with the Rest backend, but I get a message stating that 'Backend type "rest" is not supported as volume endpoint'

I know the error is pretty obvious, but I can't seem to find any documentation on why this would be the case, as the volume is mounted inside the autorestic container when it's run, shouldn't it just treat it like a bind mount?

**Comment by miguelarios** [comment]
Can you share how you have this configured in you YAML file?

**Comment by bdelcamp** [comment]
Sorry for the late reply, sidetracked with other things lately, but thanks for taking the time to check it out. It's a fairly straightforward config, nothing fancy. I typically use the S3 or local backends without issue, but in this environment, I can only get away with a rest backend. Also, when I run the initial `autorestic check` it created the repo correctly.

```yaml
backends:
  autorestic_server:
    type: rest
    path: http://10.173.192.54:8100/bookstack
    key: JB...TWQ
    env: {}
    rest:
      user: ""
      password: ""
locations:
  bookstack_config:
    from:
    - bookstack_config
    type: volume
    to:
    - autorestic_server
  bookstack_db:
    from:
    - bookstack_db
    type: volume
    to:
    - autorestic_server
version: 2
```
