### DISCUSSION TITLE
select storage classe ENV variable

### DISCUSSION THREAD

**Discussion by mariomare22** [cupcakearmy/autorestic#282] [Q&A] [answered]
Hello!
I was trying to set up my first backup to AWS S3 but I wanted to upload the files with different than STANDARD storage class.

Is it something that can be done with an ENV variable?

I know I can achieve this with S3 policies. but IMHO a nice to have.

Thanks a lot

M.

**Comment by azertylr** [comment]
hello
have you find out how to to it? I don't find how to add the option "s3.storage-class=ONEZONE_IA" with the config file

**Reply by azertylr** [reply, marked as answer]
Hello I managed to change to class (without env) by doing

```
    options:
      backup:
        option:
          s3.storage-class=ONEZONE_IA
```
