### DISCUSSION TITLE
Has anyone been able to fuse-mount a repo inside a docker container?

### DISCUSSION THREAD

**Discussion by giancarlov93** [cupcakearmy/autorestic#291] [Q&A]
I'm using this compose file for running the container

```
version: '3.3'
services:
  autorestic:
    image: cupcakearmy/autorestic:latest
    container_name: autorestic
    restart: unless-stopped
    entrypoint: watch -n 300 autorestic cron --ci -v --lean
    
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    privileged: true
```
