### DISCUSSION TITLE
unclear how to set env variables for restic rest server

### DISCUSSION THREAD

**Discussion by motey** [cupcakearmy/autorestic#321] [Q&A]
According to the docs at https://autorestic.vercel.app/backend/env :
> You can also pass whatever env variable to restic by prefixing it with `AUTORESTIC_[BACKEND NAME]_`

I would like to set `backends`.`<name>`.`path` and `backends`.`<name>`.`rest`.`user` and `backends`.`<name>`.`rest`.`password` parameter via environment variables.   
For most backend theres is  `backends`.`<name>`.`env` which is configurable via environment vairables. For the the rest backend it is not, or is it?

Examples:

**.autorestic.yaml**
```yaml
version: 2

locations:
  home:
    from: /data
    to: resticrestserver

backends:
  resticrestserver:
    type: rest
    path: http://user:pass@host:6969/path
    key: xxx
    rest:
      user: user
      password: pass

``` 
if would like overwrite this config with something like this

**.autorest.env**
```
AUTORESTIC_RESTICRESTSERVER_RESTIC_PASSWORD=mysecretkey
AUTORESTIC_RESTICRESTSERVER_PATH=https://myrestserver.domain.org:443/myuser
AUTORESTIC_RESTICRESTSERVER_REST_USER=myuser
AUTORESTIC_RESTICRESTSERVER_REST_PASSWORD=myresthttpauthpassword
```

That did not work me. Is it just not possible to set rest-server variables via env or am i stupid?
Anybody some hints for me? 
Thanks :heart:

**Comment by nadir-ishiguro** [comment]
Well, this took  me forever to figure out, but it's obvious in hindsight. Your post actually gave me the final clue.

Have a look at the possible ENV variables: https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables

The relevant ones are: 

```
RESTIC_REST_USERNAME                Restic REST Server username
RESTIC_REST_PASSWORD                Restic REST Server password
```

As we have to prepend `AUTORESTIC_[BACKEND NAME]_`, that becomes:

```
AUTORESTIC_[BACKEND NAME]_RESTIC_REST_USERNAME=Restic REST Server username
AUTORESTIC_[BACKEND NAME]_RESTIC_REST_PASSWORD=Restic REST Server password
```

Checkout https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#rest-server too.

Make sure to remove the rest: part with username and password. The env variables should be prioritized, but I find it confusing if they remain there:

Also remove `user:pass@` from the path:

```
backends:
  resticrestserver:
    type: rest
    path: http://host:6969/path
    key: xxx
```
