### DISCUSSION TITLE
Need help with autorestic + rclone in docker and error invalid backend

### DISCUSSION THREAD

**Discussion by ovizii** [cupcakearmy/autorestic#326] [Q&A]
**This is my docker-compose.yml**

```
version: '3.9'

services:

# https://autorestic.vercel.app/docker
    autorestic:
        image: cupcakearmy/autorestic:1.7
        container_name: autorestic
        hostname: autorestic
        command: 'autorestic backup -va -c /data/.autorestic.yaml'
        restart: 'no'
        cpus: 2
        mem_limit: 4G
        network_mode: host
        volumes:
            - '/root/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro'
            - './data:/data'
            - '/Documents:/mnt/documents:ro'
```
**This is my .autorestic.yaml**

```
global:
  forget:
    keep-last: 3 # always keep at least X snapshots
    keep-hourly: 24 # keep X last hourly snapshots
    keep-daily: 7 # keep X last daily snapshots
    keep-weekly: 1 # keep X last weekly snapshots
    keep-monthly: 3 # keep X last monthly snapshots
    keep-yearly: 7 # keep X last yearly snapshots
    keep-within: 2w # keep snapshots from the last X weeks
backends:
  OneDrive1TB:
    type: rclone
    path: 'OneDrive1TB:/Backups'
    key: 'redacted-password'
locations:
  documents:
    from:
      - /mnt/documents
    to:
      - OneDrive1TB
    forget: prune # Or only "yes" if you don't want to prune
version: 2
```
**This is the error:**
```
docker/autorestic# docker compose logs -f
autorestic  | Using config:      /data/.autorestic.yaml
autorestic  | Using lock:        /data/.autorestic.lock.yml
autorestic  | 
autorestic  | 
autorestic  |     Backing up location "documents"    
autorestic  | 
autorestic  | location "documents" has an invalid backend "OneDrive1TB"
autorestic  | 
autorestic  | Error: 1 errors were found
```

The rclone remote and path are correct:

```
docker run --rm -v ./data:/data -v /root/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro -v /Documents:/mnt/documents:ro cupcakearmy/autorestic:1.7 rclone lsd OneDrive1TB:/
          -1 2023-10-08 12:14:17         6 Backups
```
