### DISCUSSION TITLE
Help in setting up HOOKS

### DISCUSSION THREAD

**Discussion by mariomare22** [cupcakearmy/autorestic#330] [Q&A]
Hello!

I am trying to set up hooks to send me via ntfy the env variables. but I have no idea how to set them up
I would like upon success hook to send 
- ADDED_SIZE
- FILES_CHANGED
- FILES_ADDED

```
    hooks:
      before:
      - curl -d "Starting backup" ntfy.sh/mytag
      after:
      - curl -d "Backup Finished" ntfy.sh/mytag
      success:
      - curl -d "Backup Successful" ntfy.sh/mytag
      failure:
      - curl -d "There was an errror" ntfy.sh/mytag
```

How can I implement the variables? and the metadata?
