### DISCUSSION TITLE
Passing rclone arguments as 'option'

### DISCUSSION THREAD

**Discussion by max-dw-i** [cupcakearmy/autorestic#341] [Q&A] [answered]
I need to pass arguments to `rclone`. Here is the backend config:
```yml
backends:
    cloud:
        type: rclone
        path: cloud:backup
        options:
            backup:
                option:
                  - rclone.args='serve restic --stdio --verbose'
```
When I run `autorestic backup -a`, I get an error:
```
rclone: Error: unknown command "serve restic --stdio --verbose" for "rclone"
rclone: Run 'rclone --help' for usage.
rclone: You could use 'rclone selfupdate' to get latest features.
rclone: 
rclone: 2023/12/01 22:25:46 Fatal error: unknown command "serve restic --stdio --verbose" for "rclone"
Fatal: unable to open repository at rclone:cloud:backup: error talking HTTP to rclone: exit status 1
```
If I run the command without `options`, everything is OK. I tried different quotes, quotes around the whole string, `>`/`>-` after `option` and cannot make it work.
Here's the corresponding `restic` command:
```
restic -o rclone.args="serve restic --stdio --verbose" -r rclone:cloud:backup
```
What am I doing wrong?
