### DISCUSSION TITLE
Issues with multiple docker volumes in a single location

### DISCUSSION THREAD

**Discussion by PleaseStopAsking** [cupcakearmy/autorestic#342] [General]
I am attempting to backup multiple docker volumes in a single location but when running `autorestic config`, I am getting the error `Error: location "docker" has more than one docker volume`.

I didn't see anyone else reporting this issue with a quick search of issues and discussion so I want to see if anyone has any idea of what's going on here. Is this a limitation of docker volume locations and I need to split this into individual locations?

My other locations and backends are working fine but those are not docker volumes.

**Config:**

```
version: 2
locations:
  docker:
    from: 
      - plex
      - influxdb
    type: volume
    to: data-docker
    cron: '0 3 * * 0' # every sunday at 3:00

backends:
  data-docker:
    type: sftp
    path: {{ autorestic_ssh_name }}:/mnt/store/data/docker/{{ ansible_hostname }}
    key: {{ geordi_autorestic_backends_data_key }}
```
