### DISCUSSION TITLE
Autorestic could not read config from restic REST server - whom's't've to blame? Except me

### DISCUSSION THREAD

**Discussion by Kenya-West** [cupcakearmy/autorestic#421] [Q&A] [answered]
#### Restic

I setup a `restic` REST server with this `docker-compose.yml`:

```yaml
---

services:
  restic_rest_server:
    image: restic/rest-server:latest
    container_name: restic_rest_server
    volumes:
      - ./data:/data
    env_file:
      - .env
    ports:
      - "127.0.0.1:${PORT}:8000"
    networks:
      - somenetwork

networks:
  somenetwork:
```

and `.env`:

```dotenv
PASSWORD_FILE = "/data/.htpasswd"
PORT = 8010
OPTIONS = "--debug --log /data/log.txt"
```

The `.htpasswd` file is correct.

#### Autorestic

`.autorestic.env`

```yaml
version: 2

locations:
  home_user:
    from: /home/user
    to:
    - somehost

backends:
  somehost:
    type: rest
    path: http://sub.example.tld:22002/
    rest:
      user: user
      password: password
```

After I launch check to initialize repository, it gets error:

```sh
 $kenyawest: ~ ❯ sudo ./backup-restic-node/autorestic/scripts/check.sh
Using config:    /home/user/backup-restic-node/autorestic/config/.autorestic.yaml
Using env:       /home/user/backup-restic-node/autorestic/config/.autorestic.env
1 error(s) decoding:

* 'locations[home_user]' has invalid keys: forgetoption
Could not parse config file!
Using lock:      /home/user/backup-restic-node/autorestic/config/.autorestic.lock.yml
```

And also config is being changed from original state to this:

<details><summary>Details</summary>
<p>

```yaml
backends:
  somehost:
    type: rest
    path: http://sub.example.tld:22002/
    key: key
    requirekey: false
    env: {}
    rest:
      user: user
      password: password
    options: {}
locations:
  home_user:
    from:
    - /home/user
    type: ""
    to:
    - somehost
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options: {}
    forgetoption: ""
    copyoption: {}
version: 2
```

</p>
</details> 

\- but I guess it is OK.

I try to backup:

```sh
 $kenyawest: ~ ❯ sudo ./backup-restic-node/autorestic/scripts/update.sh
Using config:    /home/kenyawest/backup-restic-node/autorestic/config/.autorestic.yaml
Using env:       /home/kenyawest/backup-restic-node/autorestic/config/.autorestic.env
Using lock:      /home/kenyawest/backup-restic-node/autorestic/config/.autorestic.lock.yml


    Backing up location "home_user"

Backend: somehost
> Executing: /usr/local/bin/restic backup --tag ar:location:home_user /home/user
Fatal: repository does not exist: unable to open config file: <config/> does not exist
Is there a repository at the following location?
rest:http://user:***@sub.example.tld:22002/

home_user@somehost:
Fatal: repository does not exist: unable to open config file: <config/> does not exist
Is there a repository at the following location?
rest:http://user:***@sub.example.tld:22002/
exit status 10

Error: 1 errors were found
```

#### Others

The `restic` REST server log is:

```log
172.18.0.1 - - [09/Jan/2025:14:38:10 +0000] "HEAD /config HTTP/1.1" 404 10 "" "Go-http-client/1.1"
172.18.0.1 - - [09/Jan/2025:15:46:42 +0000] "HEAD /config HTTP/1.1" 404 10 "" "Go-http-client/1.1"
172.18.0.1 - - [09/Jan/2025:15:58:40 +0000] "HEAD /config HTTP/1.1" 404 10 "" "Go-http-client/1.1"
172.18.0.1 - - [09/Jan/2025:15:58:41 +0000] "HEAD /config HTTP/1.1" 404 10 "" "Go-http-client/1.1"
172.18.0.1 - - [09/Jan/2025:15:58:42 +0000] "POST /?create=true HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.0.1 - - [09/Jan/2025:15:58:42 +0000] "HEAD /config HTTP/1.1" 404 10 "" "Go-http-client/1.1"
172.18.0.1 - - [09/Jan/2025:15:58:42 +0000] "GET /keys/ HTTP/1.1" 200 2 "" "Go-http-client/1.1"
172.18.0.1 - - [09/Jan/2025:15:58:42 +0000] "GET /snapshots/ HTTP/1.1" 200 2 "" "Go-http-client/1.1"
172.18.0.1 - - [09/Jan/2025:15:58:45 +0000] "POST /keys/key HTTP/1.1" 200 0 "" "Go-http-client/1.1"
172.18.0.1 - - [09/Jan/2025:15:58:46 +0000] "POST /config HTTP/1.1" 200 0 "" "Go-http-client/1.1"
```

Which tool to blame for autorestic errors? Which config is not OK or am I doing it wrong?
