### DISCUSSION TITLE
Best way to implement check and forget/prune

### DISCUSSION THREAD

**Discussion by liambresnahan** [cupcakearmy/autorestic#86] [Q&A]
Hi All,

Autorestic has been great for me to implement a scalable backup strategy across a number of targets - thanks for all the hard work!

I'm trying to work out how to implement a best practice approach to add `check` and `forget`/`prune` into the mix. I'd like this to as much as possible not be blocking (as I have a relatively large backup set (3+TB total, 6 or 7 backends) and am trying to backup regularly (multiple schedules but as often as once an hour)). 

What's the best way to do this?

**Comment by cupcakearmy** [comment]
So would like to backup a location to multiple backends in parallel? 
At least for now autorestic does not really have parallel way to do stuff. But we could explore some options :)

**Reply by liambresnahan** [reply]
I would extend to multiple operations in parallel. i.e. if you have an autorestic config with multiple things going on (backups, forget policies, etc) and want to use autorestic to do all of that a single large backup can throw all of that out of whack, even if other restic repos are not locked at that point as autorestic doesn't run more than a single instance. It'd be awesome to be able to have all of this defined in a single place (autorestic config) and then use that to kick off the operation no matter what it is. By way of example - this is a snapshot of my config:

```
locations:
  yyyyy:
    from: 'yyyyy'
    to: 
      - local_backup1
    options:
      forget:
        keep-hourly: 24
        keep-daily: 7
        keep-weekly: 4
        keep-monthly: 12
        keep-yearly: 1
    cron: '0 * * * *'
  xxxx:
    from: 'xxxx'
    to: 
      - local_backup2
    options:
      forget:
        keep-daily: 7
        keep-weekly: 8
        keep-monthly: 4
    cron: '15 3 * * 1,3,6'
```

I have 10 of these backends with varying cron schedules and forget policies. Making this all hang together with a check/forget/prune without affecting the backup jobs is a bit of a balancing act so I'm trying to work out what the best way to achieve this might be...
