### ISSUE TITLE
S3/Wasabi backend: repository master key and config already initialized

### ISSUE THREAD

**Issue by EliotBerriot** [cupcakearmy/autorestic#1]
Hi, I'm currently investigating autorestict to automatate some of my backups.

I love that you can describe everything in a yaml file. However, when trying to backup a test directory to a non AWS S3 storage (here wasabi), the first backup works, but not subsequent one.

First backup output:

```
eliotberriot@xxx:/etc/autorestic$ sudo autorestic backup -a

Configuring Backends
wasabi-perso : Done ✓

Backing Up
config ▶ wasabi-perso : Done ✓

Finished! 🎉

```

at this point, `.autorestic.yml` contain the proper keys.

If I relaunch a backup, I get this error:

```
eliotberriot@xxx etc/autorestic$ sudo autorestic backup -a

Configuring Backends
wasabi-perso : Configuring... ⏳Could not load the backend "wasabi-perso": Fatal: create key in repository at s3:s3.wasabisys.com/backups failed: repository master key and config already initialized
```

This is the contents of my `.autorestic.yml` file:

```yaml
locations:
  config:
    from: /etc
    to: wasabi-perso
backends:
  wasabi-perso:
    type: s3
    path: s3.wasabisys.com/backups
    key: >-
      <redacted>
    AWS_ACCESS_KEY_ID: <redacted>
    AWS_SECRET_ACCESS_KEY: <redacted>
  local:
    type: local
    path: /var/backups/restic
    key: >-
      <redacted>
```

Any idea of what could be wrong?
