### ISSUE TITLE
Forget is not using policies

### ISSUE THREAD

**Issue by M4rk3tt0** [cupcakearmy/autorestic#121]
**Describe the bug**
Running `autorestic forget -av` does not remove snapshots bacause there are is no policy specified.

This is the output of the command:

```
Using config:    /home/m4rk3tt0/.autorestic.yml
Using env:       /home/m4rk3tt0/.autorestic.env


Forgetting for location "projects"

For backend "remote"
> Executing: /usr/bin/restic forget --path /home/m4rk3tt0/Projects --dry-run
no policy was specified, no snapshots will be removed
```

**Expected behavior**
Policies should be read from the .autorestic.yml file and added to the restic forget command for it to work.

**Environment**
 - OS: Manjaro ARM Linux
 - Version: 21.10
 - Autorestic: 1.4.0

**Additional context**
This is my .autorestic.yml file.
```
backends:
  remote:
    type: b2
    path: rasp-home:projects
locations:
  projects:
    from: /home/m4rk3tt0/Projects
    to:
    - remote
    cron: 0 1 * * *
    options:
      backup:
        exclude:
        - .venv
        - venv
      forget:
        keep-daily: 3
        keep-weekly: 1
```
