### ISSUE TITLE
Forget command does not remove snapshots

### ISSUE THREAD

**Issue by nateify** [cupcakearmy/autorestic#126]
**Describe the bug**
Running `autorestic forget -a --prune` shows the correct policy but no snapshots are removed.

**Expected behavior**
The snapshots listed by native restic during a dry-run with an identical policy should be removed by autorestic.

**Environment**
 - OS: Ubuntu 18.04
 - Version: Autorestic v1.4.1

**Additional context**
Here is the contents of my `.autorestic.yaml` with some censored values:
```
locations:
  home:
    from: /home2/xxx/
    to: xxx
    cron: '0 */2 * * *'
    options:
      forget:
        keep-last: 12
        keep-within : '24h'
        keep-within-daily: '5d'
        keep-within-weekly: '28d'


backends:
  xxx:
    type: rclone
    path: xxx
    key: xxx
```
If I run `autorestic exec -av -- snapshots` it shows me 105 snapshots before I run the forget command. Here is the output with paths censored: https://pastebin.com/raw/ZvZP6vGR

If I run `autorestic forget -a --prune` the following output is given:
```
Using config file: /home2/xxxxxxxxxxxxxxx/.autorestic.yml


  Forgetting for location "home"  

For backend "xxx"
> Executing: /home2/xxxxxxxxxxxxxxx/bin/restic forget --path /home2/xxxxxxxxxxxxxxx/ --prune --keep-last 12 --keep-within-weekly 28d --keep-within 24h --keep-within-daily 5d
Applying Policy: keep 12 latest snapshots, daily snapshots within 5d, weekly snapshots within 28d and all snapshots within 24h of the newest

Done
```
However if I run `autorestic exec -av -- snapshots` immediately after, it shows all 105 snapshots. Nothing is removed or pruned.

By running this `exec` command I can test the same policy: `autorestic exec -av forget -- --dry-run --keep-last 12 --keep-within 24h --keep-within-daily 5d --keep-within-weekly 28d`

And now restic shows me the output I would expect, which is removing 85 of these 105 snapshots: https://pastebin.com/raw/mnxu8TNE
