### ISSUE TITLE
version field in config file not supported 

### ISSUE THREAD

**Issue by tesujimath** [cupcakearmy/autorestic#146]
**Describe the bug**
Including a version field in the config file causes it not to be parsed.  This is unfortunate, since the [example config file](https://autorestic.vercel.app/config) includes this field.
 
**Expected behavior**

This config file works:

```
backends:
  local_backup:
    type: local
    path: /srv/backup/restic
locations:
  junk:
    from: /home/sjg/junk
    to:
    - local_backup
```

so I expected this one also to work:

```
version: 2
backends:
  local_backup:
    type: local
    path: /srv/backup/restic
locations:
  junk:
    from: /home/sjg/junk
    to:
    - local_backup
```

Rather than cause this error:
```
# autorestic check
Using config: 	 /root/.autorestic.yml
Could not parse config file!
```

**Environment**
 - OS: NixOS
 - Version: 21.11
