### ISSUE TITLE
Allow backends to fail/be skipped

### ISSUE THREAD

**Issue by cupcakearmy** [cupcakearmy/autorestic#189]
### Discussed in https://github.com/cupcakearmy/autorestic/discussions/185

<div type='discussions-op-text'>

<sup>Originally posted by **varac** April 25, 2022</sup>
I'd like to always backup to my remote location, and when I'm at home I'd also like to backup a my local NAS.
It would be great if Autorestic could be configured for this in a way that it doesn't fail if the second location is not available.
Maybe a backend config like this could do it:

```
backends:
  remote:
    type: sftp 
    path: ...
  local: 
    type: sftp
    path: ...
    only_if:
      cmd: check_local_avail.sh
      allow_fail: true
```
      
When the script `check_local_avail.sh` fails, and `only_if.allow_fail` is set to `true` autorestic should (silently) succeed.
What do you think ?</div>
