### ISSUE TITLE
support custom env variables in location

### ISSUE THREAD

**Issue by xxxsen** [cupcakearmy/autorestic#195]
**Is your feature request related to a problem? Please describe.**

in my use case, i need stop my docker container before backing up files and restart it after backing up, so i wrote config like this.

```yml
extras:
  - &succ ...
  - &fail ...

locations:
  bk1:
    from: ...
    to: ...
    hooks:
      before:
        - cd ${backup folder} && docker-compose stop
      after:
        - cd ${backup_folder} && docker-compose restart  
      success:
        - *succ
      failure:
        - *fail
  - bk2:
    - ...
```

since different location have different ${backup_folder}, I need to copy the hook part to all my locations, which is hard to maintain.

this configuration would look like this if I could pass custom environment variables.

```
extras:
  dohook: &dohook
    hooks
      before:
        - cd ${backup_folder} && docker-compose stop
      after:
        - cd ${backup_folder} && docker-compose restart  
      success:
        - ...
      failure:
        - ...

locations:
  bk1:
    from: ...
    to: ...
    env:
      - "backup_folder=/home/xxx/data/bk1"
    <<: *dohook

```
 as you can see, this code is clear than the above
 

**Describe the solution you'd like**

there are 2 solutions

1. pass ${from} variable(backup folder) to ExcuteOptions.Envs in this code block(file: internal/location.go) and command in hook part will got it.

![image](https://user-images.githubusercontent.com/3880276/168414783-cb991984-df4a-4515-b0ee-20ba1ec242ea.png)

2. add an extra config field for env and put it into ExcuteOptions.Envs.

![image](https://user-images.githubusercontent.com/3880276/168414819-24a04a24-bef3-40e3-a7bf-330cbc6bd99d.png)
