### ISSUE TITLE
"Orchestration" of multi container setups

### ISSUE THREAD

**Issue by mrclschstr** [cupcakearmy/autorestic#196]
**Is your feature request related to a problem? Please describe.**

I'm using autorestic to backup folders and single docker containers for quite some time now and I'm very happy with it! Unfortunately I stumbled upon an issue and I really cannot wrap my head around. I want to backup a Nextcloud with MariaDB container, which needs some kind of "orchestration" (see [docs](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/backup.html)):

  * **Nextcloud container:** Enable maintenance mode
  * **MariaDB container:** Create mysqldump
  * Backup files and mysqldump
  * **Nextcloud container:** Disable maintenance mode

My `.autorestic.yml` looks like this (simplified):

```yml
version: 2

backends:
  backblaze:
    type: b2
    path: <path>
    key: <key>
    env:
      b2_account_id: <b2_account_id>
      b2_account_key: <b2_account_key>

locations:
  nextcloud_app:
    type: volume
    from: nextcloud_app
    to: backblaze
    cron: '0 3 * * *'
    hooks:
      dir: 'nextcloud'
      before:
        - <enable nextcloud maintenance mode>
      after: []
      success: []
      failure:
        - <disable nextcloud maintenance mode>

  nextcloud_mariadb:
    type: volume
    from: nextcloud_mariadb
    to: backblaze
    cron: '0 3 * * *'
    hooks:
      dir: 'nextcloud'
      before:
        - <create mysqldump>
      after:
        - <remove mysqldump file>
        - <disable nextcloud maintenance mode>
      success: []
      failure:
        - <disable nextcloud maintenance mode>
```

Using clever interleaving of the hooks I can achieve my backup goal, but this only works using explicit specification of the locations: `autorestic backup -l nextcloud_app -l nextcloud_mariadb`. Using `autorestic backup -a` or `cron` processes the locations in a non-deterministic way so sometimes the location `nextcloud_mariadb` is processed before `nextcloud_app`. The hooks are useless in this case.

**Describe the solution you'd like**
I'm really not sure how to handle this. Maybe process the locations in alphabetical order? Maybe introduce something like an `order` attribute where I can choose ordering number? I'm open for suggestions 😄
