### ISSUE TITLE
Check and init command ignore YAML options

### ISSUE THREAD

**Issue by Chostakovitch** [cupcakearmy/autorestic#198]
When running `autorestic check`, at some point, autorestic runs `restic check`. However, any option in the YAML configuration file won't be passed to `restic`. Only environment is included. The code is here : https://github.com/cupcakearmy/autorestic/blob/3bc091f826704d0a95d4d500d60083bddd3dee74/internal/backend.go#L122-L124

A few lines later, `restic init` won't use YAML options neither.

Example configuration file:

```yaml
backends:
   rest:
   [...]
    options:
      all:
        cacert:
        - /var/lib/restic/certs/ca/ca_cert.pem
        tls-client-cert:
        - /var/lib/restic/certs/client_cert_with_key.pem
```

In that case TLS options are ignored and the command fails with an `unknown certificate` error.
