### ISSUE TITLE
[Feature request] forget policies

### ISSUE THREAD

**Issue by EliotBerriot** [cupcakearmy/autorestic#2]
[Restic supports pruning previous snapshots using a policy](https://restic.readthedocs.io/en/latest/060_forget.html#removing-snapshots-according-to-a-policy), and I think it could be interesting to integrate this in autorestic to ensure users don't eat storage resources indefinitely.

It could be exposed as follows (this is just suggestion):

```yaml
locations:
  etc:
    from: /etc
    to: wasabi-perso
    keep:
      last: 5             # always keep at least 5 snapshots
      hourly: 3           # keep 3 last hourly shapshots
      daily: 4            # keep 4 last daily shapshots
      weekly: 1           # keep 1 last weekly shapshots
      monthly: 12         # keep 12 last monthly shapshots
      yearly: 7           # keep 7 last yearly shapshots
      duration: 2w        # keep snapshots from the last 2 weeks
      tags:
        - important
        - critical
```

The param names and values match what's advertised in the restic documentation, for consistency and ease of implementation.

To ensure `autorestic` doesn't prune anything by accident, I suggest the addition of a separate command, mimicking the `backup` command, but to apply pruning:

```sh
autorestic forget -l etc
autorestic forget -a
```

Internally, this command would call `restic forget` with the declared policies, and `restic prune`.

Let me know what you think about it :)
