### ISSUE TITLE
Cron per backend

### ISSUE THREAD

**Issue by N-Schaef** [cupcakearmy/autorestic#216]
I could not find anything in the docs.
Is it currently possible to have different crons per backend location?

For example:
```yml
locations:
	data:
		from: /mnt/data
		to:
	                -  local
			- remote
```

And perform the local backup daily and the remote backup weekly?

I know I could use two locations for that, but this seems more like a workaround

**Comment by cupcakearmy** [comment]
That is not an option rn

**Comment by cupcakearmy** [comment]
What you could do rn is use the `extra` field and `yaml` anchors to achieve a similar behavior.
https://autorestic.vercel.app/config#aliases

```yaml
version: 2

extras:
  data: &foo
    from: /mnt/data
    # ...

locations:
  data-local:
    <<: *foo
    to: local
    cron: '0 0 0 0 0'
  
  data-remote:
    <<: *remote
    to: local
    cron: '0 0 0 1 0'
```
