### ISSUE TITLE
Could not parse config File

### ISSUE THREAD

**Issue by SkipTam** [cupcakearmy/autorestic#218]
**Describe the bug**
File .autorestic.yml was created. autorestic check was run, but if backup command is used i get the error has invalid keys: `forge
Could not parse config file!` I have tried using my own key in the file and then running "autoresic check" this works only once or twice and backup fails again with same error. I pasted the configuration here, maybe its my fault and not a bug:
```
version: 2
locations:
  mc:
    from: /data/mc119
    to: hdd
    cron: '*/30 * * * *'
    forge: prune
    options:
      forget:
        keep-Last: 30
backends:
  hdd:
    type: local
    path: /data/mcbackup
    key: secret123
```

**Expected behavior**
I'm guessing that the backup command should back up my data. 

**Environment**
 - OS: Ubuntu linux 22.04 
 - Shell ZSH
 - Version: 1.7.1 over APT

**Additional context**
I have also checked the user permissions on the file. Executed as normal user and as Root, same error exists. I'm not sure if this is a configuration error or if this is a bug. If you need any more information or test, reply what you need. Thanks!
