### ISSUE TITLE
SFTP url parsing broken

### ISSUE THREAD

**Issue by peterrus** [cupcakearmy/autorestic#222]
**Describe the bug**
I have identified two scenario's where the URL for sftp backends do not get parsed properly:

*SFTP backend with non-standard port*
```
  postapocalyptic-backup:
    type: sftp
    path: 192.168.1.100:2123:/folder
    key: "wow"
```

This gives me a:

```
subprocess ssh: ssh: connect to host 192.168.1.100 port 22: Connection refused
Fatal: unable to open repo at sftp:192.168.1.100:2022:/folder: unable to start the sftp session, error: EOF
```

(Wrong port attempted)

Probably due to the fact that we need to format it as a proper SFTP url before passing it to Restic, see: https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#sftp

>If you need to specify a port number or IPv6 address, you’ll need to use URL syntax. E.g., the repository /srv/restic-repo on [::1] (localhost) at port 2222 with username user can be specified as sftp://user@[::1]:2222//srv/restic-repo

I can work around this by formatting my `.autorestic.yml` as follows:
```
  postapocalyptic-backup:
    type: sftp
    path: //192.168.1.100:2123/folder # notice the missing colon before the '/folder'
    key: "wow"
```

It does work, but it might be a bit confusing, and not entirely intended.

**Environment**
 - OS: Ubuntu 22.04
 - Version: 1.7.1
