### ISSUE TITLE
Failure hook incorrectly called in cron

### ISSUE THREAD

**Issue by patrick-motard** [cupcakearmy/autorestic#288]
**Describe the bug**
Example yaml:
```yaml
locations:
  music:
    from: "/amazing/directory/"
    to:
      - backblaze_test
      - local_music
    cron: '* * * * *'
    hooks:
      success:
        - "echo 'music worked!'"
      failure:
        - "echo 'music failed!'"
backends:
  local_music:
    type: local
    path: mypath
    key: mykey
  backblaze_test:
    type: b2
    path: 'awesome-bucket:/test'
    env:
      B2_ACCOUNT_ID: 'secret'
      B2_ACCOUNT_KEY: 'even more secret'
    key: mykey
```

I have a location and backend set up in autorestic. I have configured autorestic to trigger on a [cron ](https://autorestic.vercel.app/location/cron)schedule on my linux (debian) server. I have set up [hooks ](https://autorestic.vercel.app/location/hooks)for both success and fail. The success and fail simply echo unique messages.

When `autorestic --ci cron` is run in the terminal, the success hook is triggered after the backup completes.
When `autorestic --ci cron` is called via cron, the failure hook is triggered. 

As suggested in the [debug ](https://autorestic.vercel.app/location/cron#crontab) portion of the crontab section in the documentation, I've set up the cron to pipe it's output to a file. There is no error output.

```
* * * * * /usr/local/bin/autorestic --ci -c /root/.autorestic.yml cron >> /tmp/autorestic.log 2>&1
```

I've tested this with only a local backend, to rule out backblaze. Same issue.

**Expected behavior**
The successful cron should trigger the success hook. If there is _any_ failure when autorestic runs, it should output the failure to stderr. I suspect there is a failure going on that is not being output. 

**Environment**
```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
restic: `restic 0.14.0 compiled with go1.19 on linux/amd64`
autorestic: `autorestic version 1.7.4`
