### ISSUE TITLE
cron: autorestic fails when location file path contains spaces

### ISSUE THREAD

**Issue by leafonthewind** [cupcakearmy/autorestic#301]
**Describe the bug**
Autorestic run via cron fails to backup a location when the local location path contains spaces.

However, given the same failing config, Autorestic run via `autorestic backup -a` *does not fail*, and backups succeed.

**Expected behavior**
A clear error message.  Consistent behavior between `autorestic backup -a` and running the same config via cron.

**Environment**
Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

Autorestic v1.7.7 (latest at time of this bug report)

**Additional context**
When the `.autorestic.yml` config contains a `from:` value in a location which has whitespace, for example:

```yaml
from: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/"
```

The backup will succeed when run using `autorestic backup -a`, but fail when run via a cron script such as:

```
PATH="/usr/local/bin:/usr/bin:/bin"

# m h  dom mon dow   command
*/5 * * * * /usr/local/bin/autorestic -c /root/.autorestic.yml --ci cron --lean >> /var/log/autorestic.log 2>&1
```

Shown in `/var/log/autorestic.log` when autorestic runs via cron and **fails**.

```
    Backing up location "plex-data"


Running hooks
> curl --max-time 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Starting backup for location: ${AUTORESTIC_LOCATION}" https://hc-ping.com/<someUUID>/start
> Executing: /usr/bin/bash -c curl --max-time 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Starting backup for location: ${AUTORESTIC_LOCATION}" https://hc-ping.com/<someUUID>/start
OK
Backend: b2
> Executing: /usr/local/bin/restic backup --tag keepShort --tag ar:cron --tag ar:location:plex-data /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/
using parent snapshot 120fa737
Signal: terminated
```

The last line `Signal: terminated` is the indication something has gone wrong.  Running `autorestic backup -a` at this point *still works*, however, the invocation from cron will never succeed.

Fwiw, `autorestic check` also throws a vague error at this point.  Exit code 1.

The **solution** is to modify the location `from:` like so:

```yaml
from: "/var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/"
```

This is a pretty low severity issue, since it can be easily worked around.  Hoping that by reporting this here the error messaging can be made more clear and/or others stumble across this issue to solve their problem.

Here is the complete configuration file.

```yaml
version: 2

extras:
  keepLong: &keepLong
    keep-last: 7
    keep-daily: 7
    keep-weekly: 5
    keep-monthly: 12
  keepShort: &keepShort
    keep-last: 7
    keep-daily: 7
    keep-weekly: 3
  keep-one: &keepOne
    keep-last: 1
  healthchecks: &healthchecks
    hooks:
      before:
        - 'curl --max-time 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Starting backup for location: ${AUTORESTIC_LOCATION}" https://hc-ping.com/<someUUID>/start'
      failure:
        - 'curl --max-time 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Backup failed for location: ${AUTORESTIC_LOCATION}" https://hc-ping.com/<someUUID>/fail'
      success:
        - 'curl --max-time 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Backup successful for location: ${AUTORESTIC_LOCATION}" https://hc-ping.com/<someUUID>'

locations:
  plex-data:
    from: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/"
    to:
      - b2
    cron: '0 2 * * *'
    forget: prune
    options:
      backup:
        tag:
          - keepShort
      forget:
        <<: *keepShort
    <<: *healthchecks

backends:
  b2:
    type: b2
    path: '<bucketName>'
    key: '<generated_on_first_run>'
    env:
      B2_ACCOUNT_ID: '<backblaze_keyID>'
      B2_ACCOUNT_KEY: '<backblaze_applicationKey>'
```
