### ISSUE TITLE
No output from "restic list snapshots", "restic stats" etc. for S3 backend

### ISSUE THREAD

**Issue by perry-mitchell** [cupcakearmy/autorestic#304]
**Describe the bug**
I'm using autorestic to backup a local mount to an S3 backend (Scaleway, not AWS). After some testing ([where `check` wouldn't work](https://github.com/cupcakearmy/autorestic/issues/194#issuecomment-1515790823)) I managed to get `check` to initialise a repo on the remote S3, and allowed a couple of backups to run. Some files are transferred and I can see the encrypted content in the S3 bucket.

When I run some restic commands (via autorestic) on the backend, however, I get no output:

```
$ autorestic exec -b <snip> stats
Using config: 	 /home/<snip>/Temp/s3_autorestic/.autorestic.yml
Using lock:	 /home/<snip>/Temp/s3_autorestic/.autorestic.lock.yml


    Executing on "<snip>"    

$
```

```
$ autorestic exec -b <snip> list snapshots
Using config: 	 /home/<snip>/Temp/s3_autorestic/.autorestic.yml
Using lock:	 /home/<snip>/Temp/s3_autorestic/.autorestic.lock.yml


    Executing on "<snip>"    

$
```

Check is OK:

```
$ autorestic check
Using config: 	 /home/<snip>/Temp/s3_autorestic/.autorestic.yml
Using lock:	 /home/<snip>/Temp/s3_autorestic/.autorestic.lock.yml
Everything is fine.
$
```

**Expected behavior**

**Environment**
 - OS: Debian 10 slim (Docker) and Ubuntu 22.04
 - Version: _See details below_

**Additional context**

My config:

```yaml
version: 2
backends:
  test:
    type: s3
    key: --snip--
    path: https://s3.fr-par.scw.cloud/--snip--/s3_backup
    env:
      AWS_ACCESS_KEY_ID: --snip--
      AWS_SECRET_ACCESS_KEY: --snip--
locations:
  test:
    from: /mnt/source/test
    to: test
    cron: "* * * * *"
```

```
$ restic version && autorestic --version
restic 0.15.1 compiled with go1.19.5 on linux/amd64
autorestic version 1.7.7
```
