### ISSUE TITLE
SFTP connection with ssh key is not possible.

### ISSUE THREAD

**Issue by kpinarci** [cupcakearmy/autorestic#307]
### Discussed in https://github.com/cupcakearmy/autorestic/discussions/306

<div type='discussions-op-text'>

<sup>Originally posted by **kpinarci** May 14, 2023</sup>
I'm unable to connect autorestic using the combination of SFTP and SSH private key.
I'm receiving the following error message: Initializing backend "sftp"...
Error: exit status 1
I'm using the following version: autorestic version 1.7.7

However, when I use the backend like this, it works, but I always have to authenticate with a password:
```yml
backends:
  sftp:
    type: sftp
    path: [xxxxx@xxxx-storagebox.de](mailto:xxxxx@xxxx-storagebox.de):/autorestic
    #path: my-storagebox.de:/autorestic
    key: xxxxxxx
```

## my .autorestic.yml
```yml
version: 2

locations:
  home:
    from: /opt/data/
    to: sftp

backends:
  sftp:
    type: sftp
    path: my-storagebox.de:/autorestic
    key: xxxx
```

## ~/.ssh/config
    
```shell
Host my-storagebox.de
  HostName xxxxx.your-storagebox.de
  Port xxx
  User xxxx
  IdentityFile /home/restic/.ssh/id_ed25519_restic
  ```  </div>
