### ISSUE TITLE
Issues with cron scheduled backups

### ISSUE THREAD

**Issue by adsanz** [cupcakearmy/autorestic#31]
Hi!

First of all, awesome project! Keep up with it this is my go-to solution for backups now!
 
So, I've configured autorestic with a cron schedule, to execute automated backups every day at 00:00 and crontab was executing the cron command as recommended on the docs, however I noticed that new snapshots are not being created, there's only 2 snapshots which I generated myself running a manual backup to test if it was an issue with the configuration, which looks fine to me. 

Next I'll leave versions, output from autorestic cron execution and part of the configuration file.

Versions:
```
root@matchbox:~# autorestic -V
0.21
root@matchbox:~# restic version
restic 0.11.0 compiled with go1.15.3 on linux/amd64
```

Output:
```
root@matchbox:~# autorestic -c /root/.autorestic.yml cron

Configuring Backends
sftp : Done ✓

Running cron jobs
files ▶ Skipping. Scheduled for: Sat Nov 14 2020 00:00:00 GMT+0000

Finished! 🎉
```

Cron command:
```
#Ansible: Autorestic cron check
PATH="/usr/local/sbin:/usr/local/bin"
*/5 * * * * autorestic -c /root/.autorestic.yml cron >> /var/log/autorestic.log 2>&1
```

Config file:
```
locations:
  files:
    cron: '0 0 * * *'
    from: /src/media
    options:
      forget:
        keep-last: 30 
    to:
      - sftp
backends:
  sftp:
    type: sftp
    path: my-sftp-server
    key: >- this-is-my-key-dont-look-at-it->:(
```
