### ISSUE TITLE
Enhancement: allow splitting backend path into base URI and backup path

### ISSUE THREAD

**Issue by ethereal-engineer** [cupcakearmy/autorestic#323]
I have a restic rest dedicated backup server that hosts multiple repositories. I am just playing around with building my first `.autorestic.yml` and it seems that anchors and aliases would work great if I could split the scheme, hostname, and domain, from the repository path. Then for each repository, all I would need to override would be the path section, and the key (which comes from a `.env` file or environment variables anyway. At present, all I can use the YAML aliases for is the type, and the rest user and password (which should also be available through the `.env` file for security purposes.

An example presently:

```yaml
backends:
  backup-server:
    type: rest
    path: https://backup-server.mydomain.com/path/to/repo
    key: # loaded from .env
    rest:
      user: user
      password: pass
```

What I'd like to be able to do is:

```yaml
backends:
  backup-server:
    type: rest
    path: path/to/repo
    key: # loaded from .env
    rest:
      url: https://backup-server.mydomain.com:8000
      user: # loaded from .env
      password: # loaded from .env
```
This would allow efficient use of YAML aliases to specify, for each repository, as distinct backends, just the path, and key.
