### ISSUE TITLE
Suggestion: Validate location after executing before hooks

### ISSUE THREAD

**Issue by Chippit** [cupcakearmy/autorestic#332]
Currently, if you have a location with a given file path that doesn't exist at the time of executing autorestic, backups will fail, even when the file will exist after before hooks are run.

```yaml
locations:
  test-location:
    from:
      - /file/does/not/yet/exist
    hooks:
      before: touch /file/does/not/yet/exist
...
```

```
stat /file/does/not/yet/exist: no such file or directory
Error: 1 errors were found
```

In this situation, before and after hooks do not run at all.

While it's feasible to create an empty version of this file in advance of executing autorestic, it does require the sort of manual intervention and custom scripting that autorestic otherwise resolves.
