### ISSUE TITLE
Docker volume backup not working from within container

### ISSUE THREAD

**Issue by YurNaybor** [cupcakearmy/autorestic#334]
**Describe the bug**
I did not managed to get backup of Docker volumes working with cupcakearmy/autorestic in Docker.

**Expected behavior**
Autorestic backing up Docker volumes.

**Environment**
 - Debian Bookworm (Docker host)
 - latest Autorestic Docker image
  

**Additional context**

Autorestic log:

```
Using config: 	 /etc/autorestic/.autorestic.yml
Using env:	 /etc/autorestic/.autorestic.env
Using lock:	 /etc/autorestic/.autorestic.lock.yml


    Backing up location "dummy"    


Running hooks
> echo "Before"
> Executing: /bin/bash -c echo "Before"
Before

Backend: local
> Executing: docker volume inspect autorestic_dummy-location

Running hooks
> echo "After"
> Executing: /bin/bash -c echo "After"
After


Running hooks
> echo "Something went wrong"
> Executing: /bin/bash -c echo "Something went wrong"
Something went wrong
```

Autorestic configuration:

```
version: 2

global:
  all:
    cache-dir: /cache
  forget:
    keep-daily: 30
    keep-weekly: 52

locations:
  dummy:
    from: autorestic_dummy-location
    type: volume
    to:
      - local
    cron: '* * * * *'  # Every minute
    forget: prune
    hooks:
      before:
        - echo "Before"
      after:
        - echo "After"
      failure:
        - echo "Something went wrong"
      success:
        - echo "Well done!"

backends:
  local:
    type: local
    path: /backends/local
```

Autorestic invocation (in container):

```
export DOCKER_HOST: tcp://docker-socket-proxy:2375
while true; do autorestic -v -c /etc/autorestic/.autorestic.yml --ci cron; sleep 10; done
```

Docker volume listing:

```
root@xxx:/# docker volume ls
DRIVER    VOLUME NAME
local     autorestic_cache
local     autorestic_dummy-location
local     autorestic_local-backend
```

If I read the code correctly, Autorestic uses the Docker CLI to interact with Docker. Now, the Docker CLI is not included in the image, thus this cannot work:

```
root@xxx:/# docker exec -ti autorestic bash
docker:/$ docker
bash: docker: command not found
```

It is also strange to see no error message related to this in the Autorestic output. It's only the invocation of the failure hook ("Something went wrong") showing that there is an issue.
