### ISSUE TITLE
'locations[storage]' has invalid keys: forgetoption

### ISSUE THREAD

**Issue by ajaskiewiczpl** [cupcakearmy/autorestic#351]
Running `autorestic backup -a` or `autorestic check` (for second time) gives error:
```
1 error(s) decoding:

* 'locations[storage]' has invalid keys: forgetoption
Could not parse config file!
```

**Environment**
 - OS: Ubuntu Server 22.04 AMD64
 - Version: autorestic version 1.7.10

**Additional context**
My yaml file:
```
version: 2

locations:
  storage:
    from: /mnt/storage/test
    to: azure
    forget: prune
    options:
      backup:
        exclude:
          - "*.log"
          - "*.tmp"
      forget:
        keep-within: "90d"
    hooks:
      before:
        - docker stop test
      after:
        - docker start test
      failure:
        - echo "Something went wrong"
      success:
        - echo "Well done!"

backends:
  azure:
    type: azure
    path: "myserver:backup/storage"
    env:
      AZURE_ACCOUNT_NAME: redacted
      AZURE_ACCOUNT_KEY: redacted
      AZURE_ACCOUNT_SAS: redacted
```

**Comment by ilium007** [comment]
Same
```

autorestic --version
autorestic version 1.7.10
```

**Comment by Ivan-Malinovski** [comment]
Same here, tried with rest-server backend
version 1.7.11

**Comment by mariomare22** [comment]
This worked for me

```
    options:
      backup:
        exclude:
        - /mnt/3
        - /mnt/2
        - /mnt/1
      forget:
        keep-last:
        - 10
        forgetoption: prune
 ```
