### ISSUE TITLE
Copy a repo

### ISSUE THREAD

**Issue by luckydonald** [cupcakearmy/autorestic#368]
**Is your feature request related to a problem? Please describe.**
I have `source1 ` and want to copy to `backend1 `

**Describe the solution you'd like**
With #145 we have a copy feature.

```yaml
location:
  from: source1
  to:
    - backend1 # fast
    - backend2 # slow
  copy:
    backend1:
      - backend3
      - backend4
```

however, how do I `copy` it ONLY from `source1` to `backend1`?

I want to basically run 
```
export RESTIC_REST_USERNAME="..." 
export RESTIC_REST_PASSWORD="..." 
restic -r ./repo copy --from-repo rest:https://${RESTIC_HOST}
```
