### ISSUE TITLE
Add a cron option to the forget/prune policies

### ISSUE THREAD

**Issue by jdumas** [cupcakearmy/autorestic#371]
**Is your feature request related to a problem? Please describe.**
This is related to #2 and #158, but somehow I don't think it's currently possible to do this.

**Describe the solution you'd like**
I would like to set a different cron option for the backup and for the forget/prune commands. For example something like this:

```yaml
locations:
  my-location:
    from: /data
    to: my-backend
    cron: '0 3 * * 0' # Every Sunday at 3:00
    forget: prune # Run forget/prune after backup
    options:
      forget:
        keep-last: 5 # always keep at least 5 snapshots
        cron: '0 0 1 * *' # Only run forget/prune once a month
```
