### ISSUE TITLE
Multiple paths in "from:"?

### ISSUE THREAD

**Issue by dbr** [cupcakearmy/autorestic#39]
With the restic CLI, you can specify multiple paths like so:

```
restic -r ... backup /home/a /home/b /home/c
```

Is there a way to do this in the autorestic config? I tried the obvious thing of specifying `from:` as a list:

```YAML
locations:
  example:
    from:
      - /home/a
      - /home/b
      - /home/c
...
```
However this gives an error of `The "path" argument must be of type string. Received an instance of Array`

What I'm trying to do is backup both `/home/ and `/etc/` (rather than backing up `/` and excluding all other root level directories). I could have multiple locations but the options (e.g exclude patterns) would need to be duplicated for each which is cumbersome
