### ISSUE TITLE
Scope forget pruning to the current host (i.e. use `--host` option)

### ISSUE THREAD

**Issue by PHLAK** [cupcakearmy/autorestic#405]
**Is your feature request related to a problem? Please describe.**

I'm attempting to set up autorestic on multiple systems sharing one common (B2) backend. When running `autorestic forget` I'd like to be able to utilize the underlying `--host` option so that only snapshots for the current host will be forgot/pruned.

From the [Removing Backup Snapshots documentation](https://restic.readthedocs.io/en/latest/060_forget.html#removing-backup-snapshots).

> you can restrict the policy to only process snapshots which have a particular hostname with the `--host` parameter, or tags with the `--tag` option.

**Describe the solution you'd like**

Add a `host` configuration option to the `forget` configuration. This option should take either a string or `true`. When set to a string it would use that value for the `--host` option value. When set to `true` it would automatically resolve the current system's hostname and pass that value as the `--host` option value.

### Examples

```yaml
global:
  forget:
    host: my-hostname # Passes '--host my-hostname'
```

```yaml
global:
  forget:
    host: true # Resolves the current host name and passes it as '--host <current_hostname>'
```
