### ISSUE TITLE
Question: One location, multiple Docker volumes, same path inside containers

### ISSUE THREAD

**Issue by rheicide** [cupcakearmy/autorestic#420]
If there are 2 containers with their volumes mounted at the same path like this:

```yaml
services:
  app1:
    volumes:
      - volume-1:/data
    # ...

  app2:
    volumes:
      - volume-2:/data
    # ...
```

And the volumes are backed up with the same location like this:

```yaml
locations:
  docker-volumes:
    from:
      - volume-1
      - volume-2
    type: volume
    # ...
```

Will `volume-2`'s data overwrite `volume-1`'s? Do we need to put them in different locations?
