### ISSUE TITLE
`autorestic`

### ISSUE THREAD

**Issue by Kenya-West** [cupcakearmy/autorestic#425]
**Describe the bug**
Definition of the `cron` in `global` section of the config leads to `autorestic cron` being launched but doing nothing, as I see in log file.

**Expected behavior**
`autorestic cron` command should work and do something and there should be log records of command working,

**Environment**
 - OS: Ubuntu
 - Version: 24.04
 - Autorestic version: 1.8.3

**Additional context**
I create the following config:

```yaml
version: 2

extras:
  backup: &backup
    exclude-file: []
  forget: &forget
    keep-last:
      - 10
    forgetoption: prune
  complete_options: &complete_options
    backup:
      <<: *backup

global:
  forget:
    keep-last: 5
    keep-daily: 4
    keep-weekly: 1
    keep-monthly: 12
    keep-yearly: 7

locations:
  home_user:
    from: /home/user
    to:
    - somehost
    options:
      <<: *complete_options
  shared_ssl:
    from: /etc/ssl/shared
    to:
    - somehost
    options:
      <<: *complete_options

backends:
  somehost:
    type: rest
    path: http://sub.example.tld:22002/
    rest:
      user: user
      password: password
```

\- and the following cron job (from `sudo`):

```cron
#Ansible: Autorestic backup
5 * * * * /home/user/backup-restic-node/autorestic/scripts/update-cron-debug.sh
```

```sh
PATH="/usr/local/bin:/usr/bin:/bin"

autorestic -c /home/user/backup-restic-node/autorestic/config/.autorestic.yaml --ci cron > /tmp/autorestic.log 2>&1
```

as you can see, it writes an output to `/tmp/autorestic.log` file, but after execution of the command only the following is written there:

```sh
 $user: ~/ ❯ sudo cat /tmp/autorestic.log
Using config:    /home/user/backup-restic-node/autorestic/config/.autorestic.yaml
Using env:       /home/user/backup-restic-node/autorestic/config/.autorestic.env
Using lock:      /home/user/backup-restic-node/autorestic/config/.autorestic.lock.yml
```

\- and that's it. The actual backup procedure does not happen. What is going on?
