### ISSUE TITLE
Running `autorestic check` breaks the YAML file by adding invalid parameters

### ISSUE THREAD

**Issue by ResponsiblyUnranked** [cupcakearmy/autorestic#428]
**Describe the bug**
When I run `autorestic check` after creating a new backend (in order to initialise the backend) it modifies my `~/.autorestic.yml` file and breaks the syntax. After running it, if I run `check` a second time I get:

```
3 error(s) decoding:

* 'locations[apps]' has invalid keys: forgetoption
* 'locations[jellyfin-config]' has invalid keys: forgetoption
* 'locations[jellyfin-media]' has invalid keys: forgetoption
Could not parse config file!
```

I did not add this `forgetoption` to my locations and the issue seems resolved when I remove it. Autorestic seems to add it to every location (amongst other properties), for example:

```
  jellyfin-config:
    from:
    - jellyfin-config
    type: volume
    to:
    - local-config
    - backblaze
    - local-two
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: ""
    options: {}
    forgetoption: ""
    copyoption: {}
```

It's that `forgetoption: ""` which `autorestic check` is adding, and then causing problems with.

Before running `autorestic check` all that I had was:

```
  jellyfin-config:
    from: jellyfin-config
    type: volume
    to: backblaze
```

**Expected behavior**
Running `autorestic check` should not break the YAML file I have already created. I also find it strange that it adds loads of empty parameters. Is it possible to not do this, as the config file is much smaller and easier to work with, as I only need a barebones setup.

**Environment**
 - Ubuntu 24.04.1 LTS
 - Autorestic Version 1.8.3

**Additional context**
It seems to happen whenever I create a new backend and then run `autorestic check`.

**Comment by waza-ari** [comment]
Exactly the same issue here, `check` seems to modify the configuration file and adding invalid parameters like the mentioned `forgetoption`. It happens when running `check` after adding a second backend, no matter if the configuration is correct or now.

**Comment by faekiva** [comment]
The fix for this is actually already merged in #402 , but it's not in a release yet, so you'll need to build it yourself in order to take advantage of it.

**Comment by lr101** [comment]
This is still the same for me. When will a new release be coming?

**Comment by clemwo** [comment]
Any update on this issue?

**Comment by Myslawek** [comment]
Still broken. I just started with restic. I am on 1.8.3 version installed through dnf on Fedora 43. I also have restic `0.19.0` installed.

I tried to run the `autorestic backup --all` to see how it behaves, but it was complaining about unitialized repository. Executing `autorestic check` resulted in initializing the repo and replacing my configuration with new one, that contains a lot of keys with empty values (`""`, `[]`, `{}`).

After that running `autorestic backup --all` produces following error:
```
1 error(s) decoding:

* 'locations[home]' has invalid keys: forgetoption
Could not parse config file!
```

Removing the `forgetoption`  solved the issue, however that should not be needed in the first place.

For the sake of completness, here is my original config placed in `~/.config/autorestic/.autorestic.yml`:
```yaml
version: 2

locations:
  home:
    from: /home/myslaw/projects/lan-vault/data/storage
    to: dummy
    cron: "*/5 * * * *"

backends:
  dummy:
    type: local
    path: /mnt/multimedia/backups/dummy
```
