### ISSUE TITLE
"sftp" is not supported as backend for docker volume?

### ISSUE THREAD

**Issue by rnwolf** [cupcakearmy/autorestic#430]
**Describe the bug**

Backup of Docker volume to sftp backend is not working.

**Expected behavior**

Backup to local drive works.
Expected the same for sft backend.
Are able to backup files from local "home"  location to "remote" backend.

**Environment**

NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
autorestic version 1.8.3
restic version : restic 0.17.3 compiled with go1.23.3 on linux/amd64

**Additional context**

Terminal output
```
root@mail:~# autorestic backup -l docker_volumes -c ./.autorestic.yml
Using config:    /root/.autorestic.yml
Using lock:      .autorestic.lock.yml

Backing up location "docker_volumes"

Backend: hdd
Backend: remote

docker_volumes@remote:
Backend type "sftp" is not supported as volume endpoint

Error: 1 errors were found
```

.autorestic.yml
```
version: 2

backends:
    remote:
        key: XXXXXXXXXXXX
        path: backup:restic-repo
        type: sftp
    hdd:
        type: local
        path: /root/my_server_storage
        key: mysecretkey

locations:

    docker_volumes:
        from:
          - mailcowdockerized_vmail-vol-1
        type: volume
        to:
          - hdd
          - remote

    home:
        #cron: 0 0 * * MON
        from: /root/test
        to: remote
```

**Comment by rnwolf** [comment]
If I comment out the remote backend for docker_volumes to backup to local hdd works file.
Backup from local home to remote also works ok.

```
root@mail:~# autorestic backup -l docker_volumes -c ./.autorestic.yml
Using config:    /root/.autorestic.yml
Using lock:      .autorestic.lock.yml
Backing up location "docker_volumes"
Backend: hdd
Done

root@mail:~# autorestic backup -l home -c ./.autorestic.yml
Using config:    /root/.autorestic.yml
Using lock:      .autorestic.lock.yml
Backing up location "home"
Backend: remote
Done
```

**Comment by nsna** [comment]
I also ran into this issue. I haven't reviewed the code, but maybe there are some limitations when the backup job runs in a docker container with system SFTP libraries. I got around this by just using rclone configured with an SFTP backend and it seems to run fine, [rclone docs](https://rclone.org/sftp/).

sample rclone.conf configured via `rclone configure`
```
[rclone-sftp]
type = sftp
host = ip/hostname
user = remote-user
pass = password123
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum
```

backend conf:
```
backends:
  rclone-sftp:
    type: rclone
    path: rclone-sftp:/path/to/repository
```
