### ISSUE TITLE
Read data from stdin

### ISSUE THREAD

**Issue by kytta** [cupcakearmy/autorestic#434]
**Is your feature request related to a problem? Please describe.**
Restic has support for [reading data from `stdin`](https://restic.readthedocs.io/en/stable/040_backup.html#reading-data-from-stdin). This feature was requested in #8, but turned down. Back then, it was hard to implement: How are you supposed to pipe stdout into a daemon, anyways? But now, it shouldn't be difficult, if autorestic would just use the `--stdin-from-command` option.

This would allow for multiple new uses, like database dumps (so, this fixes #394), or password backups. I personally would use it to pipe the output of `bw export` directly to restic. Right now, I am hacking this together with hooks to create and delete a temporary file.

**Describe the solution you'd like**
I propose a new way of setting up a Location, where `from` is not a file or a list of files, but theoretical stdin. Here is an example of what it could look like:

```yaml
locations:
  mysqldump:
    # `from` should be undefined
    stdin: true
    stdin-command: mysqldump -u root -p hunter2 database
    to: my-backend
```

Autorestic could simply forward this to restic, resulting in:

```shell
RESTIC_REPOSITORY=/path/to/my-backend RESTIC_PASSWORD=password restic backup --stdin-from-command -- mysqldump -u root -p hunter2 database
```
