### ISSUE TITLE
Failure hook is sent for a successful location when there is a failing location

### ISSUE THREAD

**Issue by kytta** [cupcakearmy/autorestic#435]
**Describe the bug**
I have two location backing up to the same repo/backend, but on different schedules and for different paths. Think of them as "an important one" with hourly backups, and "an unimportant one" with daily backups. I have had this configuration for a while, and the important files were getting backed up without problem. 

Today, I have set up healthchecks.io hooks for the important one, and got instantly notified of a failure. Upon checking, I noticed that the unimportant backup has failed, but the important one has passed. However, the overall exit code of `autorestic cron`/`autorestic backup` was non-zero, so a failure hook was issued.

**Expected behavior**
A failure hook for a location is sent _only_ if the location itself fails, not the whole autorestic run

**Environment**
 - OS: macOS
 - Version: Sequoia 15.3.2 (24D81)

**Additional context**

To replicate (caution: heavily redacted, do not run as-is):

```yaml
version: 2

locations:
  home:  # important
    from:
      - ~
    to: my-backend
    cron: "0 * * * *"
    hooks:
      before:
        - 'curl -fsS -m 10 --retry 5 --data-raw "Starting backup for location: ${AUTORESTIC_LOCATION}" https://hc-ping.com/<UUID>/start'
      failure:
        - 'curl -fsS -m 10 --retry 5 --data-raw "Backup failed for location: ${AUTORESTIC_LOCATION}" https://hc-ping.com/<UUID>/fail'
      success:
        - 'curl -fsS -m 10 --retry 5 --data-raw "Backup successful for location: ${AUTORESTIC_LOCATION}. Created snapshot ${AUTORESTIC_SNAPSHOT_ID_ONEDRIVE}" https://hc-ping.com/<UUID>'

  apps:  # unimportant
    from: /Applications
    to: my-backend
    cron: "30 10 * * *"
    forget: yes  # <--- THIS THROWS AN ERROR; should be 'yes'

backends:
  my-backend:
    type: local
    path: ~/Backups
```
