### ISSUE TITLE
Possiblity to define volumes + local paths within from (single location)

### ISSUE THREAD

**Issue by fliespl** [cupcakearmy/autorestic#447]
**Is your feature request related to a problem? Please describe.**
I have one location for all backups.

```
  locations:
    main:
      from:
        - /backup
        - /var/lib/docker/volumes/jira_confluence_home
```

I would like to use it something like that to not duplicate hooks/options etc to second location.

```
      from:
        - name: /backup
           type: local
        - name: jira_confluence_home
           type: volume
```
