### ISSUE TITLE
YAML Aliases and Anchors

### ISSUE THREAD

**Issue by sigmonsays** [cupcakearmy/autorestic#449]
Is it possible to use yaml aliases and anchors in the configuration file?

see https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd for examples

i'm trying to specify my credentials once in a `x-defaults` section like this but it only shows an error

```
x-defaults:
  x-backblaze: &backblaze
    env:
     B2_ACCOUNT_ID: "XXX"
     B2_ACCOUNT_KEY: "XXX"

backends:
  backend1:
   type: b2
   path: bucket1
    <<: *backblaze
```

The error is unexpected keys
```
1 error(s) decoding:

* '' has invalid keys: notes, x-defaults
Could not parse config file!
```
