### ISSUE TITLE
Better logging on failed backups

### ISSUE THREAD

**Issue by FuzzyMistborn** [cupcakearmy/autorestic#49]
**Describe the bug**

Running `autorestic backup -a` or even just the name of the location only seems to run the first of the "to" backends listed.  The second does not run.

**Expected behavior**

Multiple locations are backed up.

**Environment**
 - OS: [e.g. iOS] Ubuntu
 - Version: [e.g. 22] 1.0.3

**Additional context**

Here's my config:
```
backends:
  synology_docker:
    type: sftp
    path: {{main_username}}@synology:/Restic/
    key: {{ secret_restic_repo_password }}
    env: {}
  b2_docker:
    type: b2
    path: '{{ secret_restic_b2_bucket }}:/'
    key: {{ secret_restic_repo_password }}
    env:
      B2_ACCOUNT_ID: {{ secret_restic_b2_account_id }}
      B2_ACCOUNT_KEY: {{ secret_restic_b2_account_key }}
locations:
  docker:
    from: '~/docker'
    to: 
      - synology_docker
      - b2_docker
    options:
      forget:
        keep-last: 30
```
