### ISSUE TITLE
'before' hook not working as intended

### ISSUE THREAD

**Issue by TheForcer** [cupcakearmy/autorestic#52]
**Describe the bug**
To backup a database, I added a location to the autorestic config with a 'before' hook, which dumps & compresses the database and then backups the file, like this:

```
  db:
    from: /share/backup/dbs/database.sql.gz
    to:
      - hdd
      - home
    cron: '0 4 * * *'
    hooks:
      before:
        - docker exec -t app_db pg_dumpall -c -U app_user | gzip > /share/backup/dbs/database.sql.gz
        - /root/backup/restic_backup_db.sh
```
However, when starting the backup process, autorestic attempts to run the command, but then immediately terminates. No database dump and no backup is run. As seen above, putting the command in a bash script also did not help. Also no errors and such.

```
root@server ~/backup # autorestic -v backup -l db
Using config file: /root/backup/.autorestic.yml
> Executing: /usr/bin/restic snapshots
> Executing: /usr/bin/restic snapshots


    Backing up location "db"


Running hooks
> /root/backup/restic_backup_db.sh
> Executing: /bin/bash -c /root/backup/restic_backup_db.sh
root@server ~/backup #
```

Did I miss anything obvious? Running `/bin/bash -c /root/backup/restic_backup_db.sh` standalone works fine, is it the pipes maybe?

**Expected behavior**
Run database dump, then the backup :)

**Environment**
 - OS: Ubuntu 18.04
 - Version: autorestic 1.0.4

**Additional context**
autorestic is running with root privileges
