### ISSUE TITLE
Error: config could not be loaded/found

### ISSUE THREAD

**Issue by jkirkcaldy** [cupcakearmy/autorestic#63]
**Describe the bug**
Config file can't be found/read by autorestic

**Expected behavior**
config file should be read. 

**Environment**
 - OS: Unraid
 - Version: 6.9.2

**Additional context**
Changed permissions and checked ownership. I have also tried moving the config file to another location and trying to load it with the -c flag. 

I have also checked with an ubuntu 18 install with the same issue. 

The autorestic.lock.yml file is being created so it is finding the file. Just not loading it. 

I am trying to run the autorestic check command after the first install. 

I have removed the rclone lines and tried with just the minio backend but still the same issue. 

I have also run the command as root with the same issue. 

config file is bellow:
``` 
locations:
  nextclouddata:
    from: /mnt/user/NextcloudData
    to: 
      - minio
      - onedrive
    options:
      forget:
        keep-last: 5 # always keep at least 5 snapshots
        keep-weekly: 1 # keep 1 last weekly snapshots
        keep-monthly: 12 # keep 12 last monthly snapshots
        keep-yearly: 7 # keep 7 last yearly snapshots
        keep-within: '4w' # keep snapshots from the last 4 weeks      
  nextcloudweb:
    from: /mnt/disks/Docker_SSD/nextcloud
    to: 
      - minio
      - onedrive 
    options:
      forget:
        keep-last: 5 # always keep at least 5 snapshots
        keep-weekly: 1 # keep 1 last weekly snapshots
        keep-monthly: 12 # keep 12 last monthly snapshots
        keep-yearly: 7 # keep 7 last yearly snapshots
        keep-within: '4w' # keep snapshots from the last 4 weeks       
  backup:
    from: /mnt/user/Backup
    to:
      - minio
      - onedrive
    options:
      forget:
        keep-last: 5 # always keep at least 5 snapshots
        keep-weekly: 1 # keep 1 last weekly snapshots
        keep-monthly: 12 # keep 12 last monthly snapshots
        keep-yearly: 7 # keep 7 last yearly snapshots
        keep-within: '4w' # keep snapshots from the last 4 weeks 
  appdata:
    from: /mnt/disks/Docker_SSD
    to: minio
    options:
      forget:
        keep-last: 5 # always keep at least 5 snapshots
        keep-weekly: 1 # keep 1 last weekly snapshots
        keep-monthly: 12 # keep 12 last monthly snapshots
        keep-yearly: 7 # keep 7 last yearly snapshots
        keep-within: '4w' # keep snapshots from the last 4 weeks 




backends:
  name: minio
    type: s3
    path: 'minio.mydomain.com'
    key: <redacted>
    env:
      AWS_ACCESS_KEY_ID: <redacted>
      AWS_SECRET_ACCESS_KEY: <redacted>         
  name: onedrive
    type: rclone
    path: 'onedrive:/'
    key: <redacted>
```

**Comment by cupcakearmy** [comment]
What is the exact output of autorestic? is it not found or not loading?
Also I made a mistake earlier in the docs, so the quickstart example was off (i messed up 🤦‍♂️)
The backeds should be:

```yaml
backends:
  minio:
    type: s3
    path: 'minio.mydomain.com'
    key: <redacted>
    env:
      AWS_ACCESS_KEY_ID: <redacted>
      AWS_SECRET_ACCESS_KEY: <redacted>         
```

Note that there is no `name: minio`. That was my bad

**Comment by jkirkcaldy** [comment]
Changing that part of the config worked. There was an error with Rclone but I see that that hasn't been tested properly yet so have removed that and it all seems to work.  

For reference the exact error was:
`Error: config could not be loaded/found`

**Comment by cupcakearmy** [comment]
Perfect :)

For rclone I can't help you what much, never used it. However looking at the docs

- https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#other-services-via-rclone
- https://rclone.org/onedrive/

I think your config has some issues:

```yaml
  onedrive:
    type: rclone
    path: 'onedrive:/'
    key: <redacted>
```

This would generate a restic repository with the value of `rclone:onedrive:/` which I think is not compatible.
According to the docs it should be more like `rclone:onedrive:` withouth the front slash, but then again i never used it soooo yeah xD.
I'm gonna close this for now, if you are having issues with rclone open another ticket :)
