### ISSUE TITLE
Add custom tags to locations

### ISSUE THREAD

**Issue by olofvndrhr** [cupcakearmy/autorestic#69]
Add the native restic feature for adding tags to snapshots.
In restic you can use the command: "--tags" to add information to your snapshots. This comes in handy to identify or group them.
I suggest to add this feature to autorestic. My suggestion ist the following:

In restic you tag a snapshot as follows:
`restic -r /mnt/hdd backup --tag projectX --tag foo --tag bar /home/abc`

and the same in the autorestic.yml file would be:
```
locations:
  homefolder:
    from: /home/abc
    to:
      - hdd
    tags:
      - projectX
      - foo
      - bar
  
backends:
  hdd:
    type: local
    path: /mnt/hdd
```

This is just a suggested layout by me. How you implement it is of course your choice.
