### ISSUE TITLE
[Feature request] Support excludes

### ISSUE THREAD

**Issue by EliotBerriot** [cupcakearmy/autorestic#7]
[Restic supports excluding paths when backuping locations](https://restic.readthedocs.io/en/latest/040_backup.html#excluding-files), and I think it's an important feature to reduce the size of backups.

Configuration could look like this:

```yaml

locations:
  etc:
    from: /etc
    to: local
    exclude:
      - *.bak

```

I'm willing to implement this if this is something that you wish to see included :)

**Comment by cupcakearmy** [comment]
Good idea. Might be a good idea to have a general approach to passing arguments.

https://restic.readthedocs.io/en/latest/040_backup.html#excluding-files

meybe something along the lines of:

```
locations:
  something: 
    from: /la/fu
    to: local
    options:
      exclude:
        - *.whatever
      exclude-file:
        - .gitignore
```

Then one could use every flag that is available to restic

**Comment by EliotBerriot** [comment]
Makes sense. Since the options need to be passed to only specific `restic` commands, such as `backup` or `forget`, maybe this would be slightly better?

```yaml
locations:
  something: 
    from: /la/fu
    to: local
    options:
      init:
        verbose:
      backup:
        exclude:
          - *.whatever
        exclude-file:
          - .gitignore
```
