### ISSUE TITLE
Support for multiple folders

### ISSUE THREAD

**Issue by SebDanielsson** [cupcakearmy/autorestic#71]
I read the docs but couldn't find any way to backup multiple folders in one snapshot.

This is how you would do it in restic:
restic backup /root /compose /var/lib/docker/volumes

I tried two things in .autorestic.yml:

A:
```
locations:
  docker-compose:
    from: /root /compose /var/lib/docker/volumes
    to: wasabi-linode1
```

B:
```
locations:
  docker-compose:
    from:
      - /root
      - /compose
      - /var/lib/docker/volumes
    to: wasabi-linode1
```

Any way to do this with autorestic?😊
