### ISSUE TITLE
S3 Init and Backup fails with `Fatal: Unmarshal: invalid character 'b' after top-level value`

### ISSUE THREAD

**Issue by liambresnahan** [cupcakearmy/autorestic#73]
**Describe the bug**
S3 backup (onto a QNAP running QuObjects), on init and first backup I would expect to see it complete as expected but I see the below error. `.autorestic.yml` is:

```
backends:
  local_appdata:
    type: s3
    path: 'http://xxx.xxx.xxx.xxx:8010/appdata'
    key: {{key}}
    env:
      AWS_ACCESS_KEY_ID: {{key}}
      AWS_SECRET_ACCESS_KEY: {{key}}
locations:
  appdata:
    from: '/home/test/appdata'
    to: 
      - local_appdata
    options:
      forget:
        keep-hourly: 24
        keep-daily: 7
        keep-weekly: 4
        keep-monthly: 12
        keep-yearly: 1
```

Error that's presented is as such:

```
sudo autorestic backup -av
Using config file: /home/test/.autorestic.yml
> Executing: /usr/bin/restic snapshots
Initializing backend "local_appdata"...
> Executing: /usr/bin/restic init
created restic repository c07c1ae905 at s3:http://xxx.xxx.xxx.xxx:8010/appdata
```

`Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.`

`Backing up location "appdata"`

```
Backend: local_appdata
> Executing: /usr/bin/restic backup .
Fatal: Unmarshal: invalid character 'b' after top-level value
```

```
exit status 1
Error: 1 errors were found
```

**Expected behavior**
Bucket is initialized and backed up as expected.

**Environment**
 - OS: Debian
 - Version: 10.9

**Additional context**
`restic 0.12.0 compiled with go1.15.8 on linux/amd64`
