### ISSUE TITLE
Running different hooks depending on the success or failure of the backup

### ISSUE THREAD

**Issue by ptoulouse** [cupcakearmy/autorestic#74]
Would it be possible to have hooks to run different set of commands depending on the success or failure of a backup?

Something like this overly simplified example:
```
locations:
  my-location:
    from: /data
    to: my-backend
    hooks:
      before:
        - echo "Starting backup"
      after:
        - echo "Backup completed"
      success:
        - echo "Backup successful"
      failure:
        - echo "Backup failed"
```
