### ISSUE TITLE
Allow "forget" policies per backend

### ISSUE THREAD

**Issue by nicokaiser** [cupcakearmy/autorestic#81]
Currently, "forget" policies can be set per location. However, when backing up multiple locations, one might want to apply the same policies to all locations. It might be very handy to be able to also specify these policies per backend:

Instead of:

```yaml
locations:
  home:
    from: /home
    to: nas
    options:
      forget:
        keep-last: 5
        keep-daily: 7
        keep-weekly: 4
        keep-monthly: 12

  opt-containers:
    from: /opt/containers
    to: nas
    options:
      forget:
        keep-last: 5
        keep-daily: 7
        keep-weekly: 4
        keep-monthly: 12

backends:
  nas:
    type: rclone
    path: diskstation:NetBackup/server/restic
    key: '…'
```

It could simple be:

```yaml
locations:
  home:
    from: /home
    to: nas

  opt-containers:
    from: /opt/containers
    to: nas

backends:
  nas:
    type: rclone
    path: diskstation:NetBackup/server/restic
    key: '…'
    options:
      forget:
        keep-last: 5
        keep-daily: 7
        keep-weekly: 4
        keep-monthly: 12
```

When running restic directly, this is possible by just specifying the parameters:

```
restic forget -r rclone:diskstation:NetBackup/server/restic --keep-last 5 --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --prune
```
