### ISSUE TITLE
Docker Backup doesn't work with rclone backends

### ISSUE THREAD

**Issue by MattieX** [cupcakearmy/autorestic#84]
**Describe the bug**
Backing up using native Docker Volume Support described on the documentation doesn't appear to work with an Rclone backend is specified in the .autorestic.yml file

**Expected behavior**
Due to restic supporting Rclone, I expected being able to backup Docker Volumes with the method explained [here](https://autorestic.vercel.app/location/docker)

**Environment**
 - OS: Ubuntu 2020.04.2
- Latest Autorestic Release

**Additional context**
*Example .autorestic.yml*
```
backends:
  onedrive:
    type: rclone
    path: onedrive:<path>
    key: <rclone-autogenerated-key>
locations:
  docker-volume:
    from: volume:<docker-volume-name>
    to:
      - onedrive
```

By using `autorestic backup -a -v `to see the verbose output - what appears to be happening is the docker run command is issued with an entrypoint where the docker volume is specified in the .autorestic.yml but an error message is thrown:
`Fatal: unable to open repo at rclone:<autorestic_backup_name>:<path_on_remote>: exec: "rclone": executable file not found in $PATH.`

Therefore, I can assume that this implementation is not compatible as the rclone executable is not visible from within the restic container by default.
