### ISSUE TITLE
Error : "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by greentin** [cupcakearmy/autorestic#88]
Hello,

First of all, thanks for your work.

I don't know if the following error is a bug or a misconfiguration.

Anyway, here it is:

**Describe the bug**
When I run autorestic info or autorestic backup -a, I get this error message: 

> user@host:~$ autorestic backup -a
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7e95d9]
> 
> goroutine 1 [running]:
> github.com/cupcakearmy/autorestic/internal.GetAllOrSelected(0xb84de0, 0x0, 0x0, 0x4a9dca, 0x203000, 0x203000, 0x203000)
>         /home/runner/work/autorestic/autorestic/internal/config.go:157 +0x659
> github.com/cupcakearmy/autorestic/cmd.glob..func1(0xb84de0, 0xc000045380, 0x0, 0x1)
>         /home/runner/work/autorestic/autorestic/cmd/backup.go:22 +0x9d
> github.com/spf13/cobra.(*Command).execute(0xb84de0, 0xc000045370, 0x1, 0x1, 0xb84de0, 0xc000045370)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
> github.com/spf13/cobra.(*Command).ExecuteC(0xb852e0, 0xb46278, 0x94a3f0, 0x93d088)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
> github.com/cupcakearmy/autorestic/cmd.Execute()
>         /home/runner/work/autorestic/autorestic/cmd/root.go:33 +0x2d
> main.main()
>         /home/runner/work/autorestic/autorestic/main.go:41 +0x2a
> 

**Expected behavior**
Having some info on autorestic or doing a backup of my listed folders and docker volumes.

**Environment**
 - OS: Ubuntu 20.04 LTS in a Byhive VM
 - Version: autorestic 1.1.1
 
**Additional context**

**Comment by cupcakearmy** [comment]
Hey there :)

Could you post your config? (replacing your encryption keys with *** of course )

**Comment by greentin** [comment]
Hi,

Thanks for your reply.

I don't think my config is causing this error because when I use the command "autorestic check", I've this error message:

```
user@host:~$ autorestic check
Error: config could not be loaded/found
```

Anyway, my config is as follow :-) :

```
locations:
  home:
    from: /home/user
    to: hdd

  - name: paperless
    from: volume:pgdata
    to:
      - hdd

backends:
  hdd:
    type: local
    path: /srv/restic-repo
    key: '***'

```

**Comment by cupcakearmy** [comment]
I see. Where is your config located?

**Comment by cupcakearmy** [comment]
Oh wait no that is wrong, that is badly formatted. 

```
- name: paperless
    from: volume:pgdata
    to:
      - hdd
```

Should be 

```
  paperless:
    from: volume:pgdata
    to:
      - hdd
```
