### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ethindp** [cupcakearmy/autorestic#89]
**Describe the bug**

After a few runs of autorestic, I receive this panic and I can no longer use the program.

**Expected behavior**

This should *never* happen.

**Environment**
 - OS: Arch Linux
 - Version: N/A

**Additional context**

The full backtrace is as follows:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7edbf9]

goroutine 1 [running]:
github.com/cupcakearmy/autorestic/internal.GetAllOrSelected(0xb8a0a0, 0x0, 0x0, 0x4aba2a, 0x203000, 0x203000, 0x203000)
	/home/ethin/go/pkg/mod/github.com/cupcakearmy/autorestic@v1.1.1/internal/config.go:157 +0x659
github.com/cupcakearmy/autorestic/cmd.glob..func1(0xb8a0a0, 0xc000047380, 0x0, 0x1)
	/home/ethin/go/pkg/mod/github.com/cupcakearmy/autorestic@v1.1.1/cmd/backup.go:22 +0x9d
github.com/spf13/cobra.(*Command).execute(0xb8a0a0, 0xc000047370, 0x1, 0x1, 0xb8a0a0, 0xc000047370)
	/home/ethin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xb8a5a0, 0xb4b4d8, 0x94f570, 0x942128)
	/home/ethin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ethin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cupcakearmy/autorestic/cmd.Execute()
	/home/ethin/go/pkg/mod/github.com/cupcakearmy/autorestic@v1.1.1/cmd/root.go:33 +0x2d
main.main()
	/home/ethin/go/pkg/mod/github.com/cupcakearmy/autorestic@v1.1.1/main.go:41 +0x2a
```

**Comment by ethindp** [comment]
I accidentally included some extraneous terminal output. Edited the first comment to get rid of that. Apologies. (I did try reinstalling with `go install` but I get the same behaviour.)

**Comment by cupcakearmy** [comment]
that is interesting. 

Can you maybe post your redacted config?

**Comment by ethindp** [comment]
Sorry for not replying to this issue sooner -- I got majorly distracted. My redacted config is below:

```yaml
backends:
  boot:
    type: b2
    path: ethins-computer-backups:system76-lemur/boot
    key: 
    env:
      b2_account_id: 
      b2_account_key: 
  etc:
    type: b2
    path: ethins-computer-backups:system76-lemur/etc
    key: 
    env:
      b2_account_id: 
      b2_account_key: 
  home:
    type: b2
    path: ethins-computer-backups:system76-lemur/home
    key: 
    env:
      b2_account_id: 
      b2_account_key: 
  mnt:
    type: b2
    path: ethins-computer-backups:system76-lemur/mnt
    key: 
    env:
      b2_account_id: 
      b2_account_key: 
locations:
  boot:
    from: /boot
    to:
    - boot
  etc:
    from: /etc
    to:
    - etc
  hdd:
    from: /mnt
    to:
    - mnt
    hooks:
        before:
                - mount /dev/disk/by-id/ata-ST2000LM015-2E8174_WDZ2790S-part1 /mnt
        after:
                - umount /mnt
  home:
    from: /home
    to:
    - home
    hooks:
      before:
        - echo "Generating package list"
        - yay -Qqe > $HOME/pkglist
        - yay -Qqm >> $HOME/pkglist
      after:
        - echo "Erasing package list"
        - rm $HOME/pkglist
```

The `~/.autorestic.lock.yml` file looks like this, if you need it:

```yaml
running: false
```

**Comment by Extarys** [comment]
I don't want to spam saying "same!" but I thought I would give my context here as well as I installed this for the first time today. No backups were done yet.

I have this exact output using arm64 binary on a Pi 4 (64 bit Ubuntu) with the following config:
```
locations:
  vaultwarden:
    from: /data/vaultwarden
    to: nas
    hooks:
      before:
        - "docker exec -i postgres /bin/bash -c "PGPASSWORD=something pg_dump --username backup vaultwarden" > vaultwarden.sql"
    cron: '0 */4 * * *'
    options:
      forget:
        keep-last: 5 # always keep at least x snapshots
        keep-hourly: 1 # keep x last hourly snapshots
        keep-daily: 2 # keep x last daily snapshots
        keep-weekly: 1 # keep x last weekly snapshots
        keep-monthly: 3 # keep x last monthly snapshots
        keep-yearly: 2 # keep x last yearly snapshots
        keep-within: '2w' # keep snapshots from the last x weeks

backends:
  nas:
    type: local
    path: /mnt/NASBackup
```

```
$ autorestic info
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x35e148]

goroutine 1 [running]:
github.com/cupcakearmy/autorestic/internal.(*Config).Describe(0x0)
        /home/runner/work/autorestic/autorestic/internal/config.go:62 +0x28
github.com/cupcakearmy/autorestic/cmd.glob..func7(0x700320, 0x737f28, 0x0, 0x0)
        /home/runner/work/autorestic/autorestic/cmd/info.go:12 +0x24
github.com/spf13/cobra.(*Command).execute(0x700320, 0x737f28, 0x0, 0x0, 0x700320, 0x737f28)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x6ff1a0, 0x6c0278, 0x4c2170, 0x4b4f00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x268
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cupcakearmy/autorestic/cmd.Execute()
        /home/runner/work/autorestic/autorestic/cmd/root.go:33 +0x30
main.main()
        /home/runner/work/autorestic/autorestic/main.go:41 +0x24
```

I know I shouldn't (probably) put the postgres password in there but I have no idea where to put it XD
