### ISSUE TITLE
Support for YAML references/inheritance

### ISSUE THREAD

**Issue by g-a-c** [cupcakearmy/autorestic#93]
**Is your feature request related to a problem? Please describe.**

I was looking to backup several directories which have common options (tags, retention periods, etc). It would be nice to be able to include these in the YAML config as `aliases` and then inherit them later, for example:

```yaml
aliases:
  system: &system
    to:
      - remote
    options:
      backup:
        exclude-if-present:
          - .nobackup
          - CACHEDIR.TAG
        # exclude-caches: true
        exclude-file:
          - /etc/restic/excludes
        tag:
          - system-data
      forget:
        group-by: "host,tags"
        keep-within: '24h'
        keep-daily: 31
        keep-weekly: 104
        keep-monthly: 60
locations:
  etc:
    <<: *system
    from: /etc
  root:
    <<: *system
    from: /root
  srv:
    <<: *system
    from: /srv
```

However this is impossible because `autorestic` panics on seeing the unexpected `aliases` key

_edited to add context:_ previously I have achieved this with a single `restic` command line that specifies multiple paths, however this approach doesn't seem to be supported by `autorestic` as the documentation does not state that `from:` may be a list/array, only a single string.

**Describe the solution you'd like**

Something whereby `autorestic` checks for YAML keys that it _requires_ being present (i.e. `locations` and `backends`) but does not panic on extra data being included

**Comment by cupcakearmy** [comment]
Added an `extras` global config entry for storing aliases. Will release in the next version :)

**Comment by g-a-c** [comment]
```yaml
---
locations:
  personal:
    from: /home/me
    to:
      - b2
    options:
      backup:
        host: home-server
        exclude-if-present:
          - .nobackup
          - CACHEDIR.TAG
        # exclude-caches: true
        exclude-file:
          - /etc/restic/excludes
        tag:
          - me
      forget:
        host: home-server
        group-by: "host,tags"
        keep-within: '24h'
        keep-daily: 31
        keep-weekly: 104
        keep-monthly: 60
  etc: &system
    from: /etc
    to:
      - b2
    options:
      backup:
        host: home-server
        exclude-if-present:
          - .nobackup
          - CACHEDIR.TAG
        # exclude-caches: true
        exclude-file:
          - /etc/restic/excludes
        tag:
          - system
      forget:
        host: home-server
        group-by: "host,tags"
        keep-within: '24h'
        keep-daily: 31
        keep-weekly: 104
        keep-monthly: 60
  root:
    <<: *system
    from: /root
  srv:
    <<: *system
    from: /srv
backends:
  b2:
    type: b2
    path: 'redacted'
    key: 'redacted; this is the repo key from when I first set the repo up as I am "importing" an existing repo into autorestic'
    env:
      B2_ACCOUNT_ID: 'redacted'
      B2_ACCOUNT_KEY: 'redacted'
```
