### ISSUE TITLE
Better error handling on missing/wrong config

### ISSUE THREAD

**Issue by g-a-c** [cupcakearmy/autorestic#94]
**Describe the bug**

I can't run `autorestic exec` commands

```sh
root@toothrot:/tmp# autorestic exec -av -- snapshots
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7e8faf]

goroutine 1 [running]:
github.com/cupcakearmy/autorestic/internal.GetAllOrSelected(0xb85f60, 0x1, 0x0, 0x8406a0, 0xc000069ef8, 0xc0000786c0, 0xc00014dcc8)
        /home/runner/work/autorestic/autorestic/internal/config.go:153 +0x4f
github.com/cupcakearmy/autorestic/cmd.glob..func5(0xb85f60, 0xc000067dd0, 0x1, 0x3)
        /home/runner/work/autorestic/autorestic/cmd/exec.go:20 +0x9d
github.com/spf13/cobra.(*Command).execute(0xb85f60, 0xc000067da0, 0x3, 0x3, 0xb85f60, 0xc000067da0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xb852e0, 0xb46278, 0x94a3f0, 0x93d088)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cupcakearmy/autorestic/cmd.Execute()
        /home/runner/work/autorestic/autorestic/cmd/root.go:33 +0x2d
main.main()
        /home/runner/work/autorestic/autorestic/main.go:41 +0x2a



root@toothrot:/tmp# autorestic exec
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7e8faf]

goroutine 1 [running]:
github.com/cupcakearmy/autorestic/internal.GetAllOrSelected(0xb85f60, 0x1, 0x0, 0x8406a0, 0xc0000a3ae8, 0xc0000be6c0, 0xc00011bcc8)
        /home/runner/work/autorestic/autorestic/internal/config.go:153 +0x4f
github.com/cupcakearmy/autorestic/cmd.glob..func5(0xb85f60, 0xbbe0a8, 0x0, 0x0)
        /home/runner/work/autorestic/autorestic/cmd/exec.go:20 +0x9d
github.com/spf13/cobra.(*Command).execute(0xb85f60, 0xbbe0a8, 0x0, 0x0, 0xb85f60, 0xbbe0a8)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xb852e0, 0xb46278, 0x94a3f0, 0x93d088)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cupcakearmy/autorestic/cmd.Execute()
        /home/runner/work/autorestic/autorestic/cmd/root.go:33 +0x2d
main.main()
        /home/runner/work/autorestic/autorestic/main.go:41 +0x2a
```

**Expected behavior**

Not to panic, and to show me a list of stored snapshots (or whatever the command I ran should show)

**Environment**
 - OS: Linux
 - Version: 1.1.2

**Additional context**

**Comment by cupcakearmy** [comment]
Could you provide the config file? (redacted of course :))

**Comment by g-a-c** [comment]
```yaml
---
locations:
  personal:
    from: /home/me
    to:
      - b2
    options:
      backup:
        host: home-server
        exclude-if-present:
          - .nobackup
          - CACHEDIR.TAG
        # exclude-caches: true
        exclude-file:
          - /etc/restic/excludes
        tag:
          - me
      forget:
        host: home-server
        group-by: "host,tags"
        keep-within: '24h'
        keep-daily: 31
        keep-weekly: 104
        keep-monthly: 60
  etc: &system
    from: /etc
    to:
      - b2
    options:
      backup:
        host: home-server
        exclude-if-present:
          - .nobackup
          - CACHEDIR.TAG
        # exclude-caches: true
        exclude-file:
          - /etc/restic/excludes
        tag:
          - system
      forget:
        host: home-server
        group-by: "host,tags"
        keep-within: '24h'
        keep-daily: 31
        keep-weekly: 104
        keep-monthly: 60
  root:
    <<: *system
    from: /root
  srv:
    <<: *system
    from: /srv
backends:
  b2:
    type: b2
    path: 'redacted'
    key: 'redacted; this is the repo key from when I first set the repo up as I am "importing" an existing repo into autorestic'
    env:
      B2_ACCOUNT_ID: 'redacted'
      B2_ACCOUNT_KEY: 'redacted'
```
